[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 28, column 3 through line 29, column 23) Field \"\u001B[34mheader\u001B[39m\" has value\n\n\u001B[34mbody: \n  nav class=\"navbar\"\u001B[39m\n\nThe value must instead be a string.\n27: \u001B[34mheader: \u001B[39m\n28: \u001B[34m  body: \u001B[39m\n     ~~~~~~~\n29: \u001B[34m    nav class=\"navbar\"\u001B[39m\n   ~~~~~~~~~~~~~~~~~~~~~~~\n30: \u001B[34meditor: visual\u001B[39m\n\u001B[31m✖\u001B[39m The value\n\n\u001B[34mbody: \n  nav class=\"navbar\"\u001B[39m\n\nis of type object.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mheader\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42120\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82871\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82723\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///usr/lib/rstudio/resources/app/bin/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m90654\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
